🚀 ⚡️ add priorized fitting scripts

diff --git a/templates/join_cats.tmpl b/templates/join_cats.tmpl
--- a/templates/join_cats.tmpl
+++ b/templates/join_cats.tmpl
@@ -31,3 +31,12 @@ python join_catalogues.py --epochs "${mosaicnm}_catalogues.csv" --refcat "${mosa
 
 # Note the nextflow has a line that makes a new rescaled .csv file, I already make it in the prep python script so no need 
 python join_cataloges.py --epochs "${mosaicnm}_catalogues_rescaled.csv" --refcat "${mosaicnm}_${comb_freq}_comp_rescaled.fits" --out "${mosaicnm}_joined_rescaled_comp.vot" --all 
+
+
+if [[ -e "${mosaicnm}_joined_rescaled_comp.vot" ]]
+then
+    echo "Combined catalogues! Successful!!"
+else
+    echo "Failed! Could not join catalogues"
+    exit 1
+fi
diff --git a/templates/priorized_fitting.tmpl b/templates/priorized_fitting.tmpl
--- a/templates/priorized_fitting.tmpl
+++ b/templates/priorized_fitting.tmpl
@@ -70,7 +70,7 @@ echo "jobid: ${jobid}"
 echo "taskid: ${taskid}"
 echo "chan: ${channel}"
 
-track_task.py start_mosaic  --jobid="${jobid}" --taskid="${taskid}"  --start_time="$(date +%s)"
+# track_task.py start_mosaic  --jobid="${jobid}" --taskid="${taskid}"  --start_time="$(date +%s)"
 
 
 
@@ -88,3 +88,12 @@ aegean \
 
 python mosaic_global_rescale.py "${imname}_ddmod_comp.fits" "${imname}_ddmod.fits" "${GXBASE}/models/GGSM_sparse_unresolved.fits" --plot --verbose --apply --sigma-thres 75
 
+# TODO: Add check if successful, need to knwo what the output of globalrescale will be 
+
+# if [[ -e "${mosaicnm}_joined_rescaled_comp.vot" ]]
+# then
+#     echo "Combined catalogues! Successful!!"
+# else
+#     echo "Failed! Could not join catalogues"
+#     exit 1
+# fi
