updated zip to tar filename

diff --git a/templates/manta.tmpl b/templates/manta.tmpl
--- a/templates/manta.tmpl
+++ b/templates/manta.tmpl
@@ -7,6 +7,7 @@ echo ${GXBASE}
 pipeuser=PIPEUSER
 base=BASEDIR
 obslist=OBSLIST
+stem=STEM
 
 # start download
 cd "${base}" || exit 1
@@ -24,40 +25,48 @@ mwa_client --csv="${obslist}_manta.tmp" --dir="${base}"
 n=1
 for obsnum in $list
 do
-    if [[ -e "${obsnum}_ms.zip" ]]
+    if [[ "$stem" == 'ms' ]]
     then
-        if [[ ! -d "${obsnum}" ]]
+        if [[ -e "${obsnum}_*.zip" ]]
         then
-            mkdir "${obsnum}"
-        fi
-
-        cd "${obsnum}" || exit 1
-
-        if [[ -d "${obsnum}.ms" ]]
-        then
-            echo "${obsnum}.ms already exists; please remove directory before running unzip job."
-            track_task.py fail --jobid="${SLURM_JOBID}" --taskid="${n}" --finish_time="$(date +%s)"
-        else
-            mv "../${obsnum}_ms.zip" ./
-            unzip "${obsnum}_ms.zip"
-            if [[ $? ]]
+            if [[ ! -d "${obsnum}" ]]
             then
-                rm "${obsnum}_ms.zip"
-                track_task.py finish --jobid="${SLURM_JOBID}" --taskid="${n}" --finish_time="$(date +%s)"
-            else
-                echo "Failed to unzip ${obsnum}_ms.zip"
-                track_task.py fail --jobid="${SLURM_JOBID}" --taskid="${n}" --finish_time="$(date +%s)"
+                mkdir "${obsnum}"
             fi
+
+            cd "${obsnum}" || exit 1
+
+            if [[ -d "${obsnum}.ms" ]]
+            then
+                echo "${obsnum}.ms already exists; please remove directory before running unzip job."
+                track_task.py fail --jobid="${SLURM_JOBID}" --taskid="${n}" --finish_time="$(date +%s)"
+            else
+                mv "../${obsnum}_*.zip" ./
+                unzip "${obsnum}_*.zip"
+                if [[ $? ]]
+                then
+                    rm "${obsnum}_ms.zip"
+                    track_task.py finish --jobid="${SLURM_JOBID}" --taskid="${n}" --finish_time="$(date +%s)"
+                else
+                    echo "Failed to unzip ${obsnum}_ms.zip"
+                    track_task.py fail --jobid="${SLURM_JOBID}" --taskid="${n}" --finish_time="$(date +%s)"
+                fi
+            fi
+            cd ../
         fi
-        cd ../
-    elif [[ -e "${obsnum}_vis.zip" ]]
+    fi
+    
+    if [[ "$stem" == 'vis' ]]
     then
-        echo "${obsnum}_vis.zip downloaded successfully; now run cotter."
-        track_task.py finish --jobid="${SLURM_JOBID}" --taskid="${n}" --finish_time="$(date +%s)"
-        track_task.py obs_status --obs_id="${obsnum}" --status='downloaded'
-    else
-        echo "${obsnum}_ms.zip failed to download."
-        track_task.py fail --jobid="${SLURM_JOBID}" --taskid="${n}" --finish_time="$(date +%s)"
+        if [[ -e "${obsnum}_*.zip" ]]
+        then
+            echo "${obsnum}_vis.zip downloaded successfully; now run cotter."
+            track_task.py finish --jobid="${SLURM_JOBID}" --taskid="${n}" --finish_time="$(date +%s)"
+            track_task.py obs_status --obs_id="${obsnum}" --status='downloaded'
+        else
+            echo "${obsnum}_ms.zip failed to download."
+            track_task.py fail --jobid="${SLURM_JOBID}" --taskid="${n}" --finish_time="$(date +%s)"
+        fi
     fi
     ((n+=1))
 done
