⚡️ add check if pass at end

diff --git a/templates/prepmosaic.tmpl b/templates/prepmosaic.tmpl
--- a/templates/prepmosaic.tmpl
+++ b/templates/prepmosaic.tmpl
@@ -11,3 +11,11 @@ mosaicnm=MOSAICNM
 cd "${base}" || exit 1
 
 python filter_badionosphere.py --refcat "${GXBASE}/models/NVSS_SUMSS_psfcal.fits" "${mosaicnm}.txt"
+
+if [[ -e ${mosaicnm}_good_obsids.txt ]]
+then
+    echo "Quality check successful!!"
+else
+    echo "Quality check failed, cannot find the txt file with good obsids"
+    exit 1
+fi
