🐛 fix default directory bug

diff --git a/templates/priorized_fitting.tmpl b/templates/priorized_fitting.tmpl
--- a/templates/priorized_fitting.tmpl
+++ b/templates/priorized_fitting.tmpl
@@ -95,10 +95,10 @@ mosaic_global_rescale.py "${imname}_ddmod_prior_comp.fits" "${imname}_ddmod.fits
 
 # TODO: Add check if successful, need to knwo what the output of globalrescale will be 
 
-# if [[ -e "${mosaicnm}_joined_rescaled_comp.vot" ]]
-# then
-#     echo "Combined catalogues! Successful!!"
-# else
-#     echo "Failed! Could not join catalogues"
-#     exit 1
-# fi
+if [[ -e "${mosaicnm}_ddmod_prior_comp_rescaled.fits" ]]
+then
+    echo "Created priorized fit! Successful!!"
+else
+    echo "Failed! Could not make catalogue"
+    exit 1
+fi
